---
title: "RAB234_Trpn_Mrpl28_RNAseq_report"
author: "Marion Hardy"
date: "2023-06-15"
output: 
  html_document:
    toc: true 
    theme: spacelab 
    highlight: monochrome
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, cache = TRUE, echo = FALSE, warning = F, cache.lazy = F)
knitr::opts_chunk$set(fig.width=10, fig.height=15) 

library(rjson)
library(tidyverse)
library(ggrepel)
library(clusterProfiler)
library(msigdbr)
library(readxl)

```


```{r Data loading, include=FALSE}

res_tbl <- read_csv("./data_output/Trpn_Mrpl_vs_Scr/res_tbl.csv")
diff <- read_csv("./data_output/Trpn_Mrpl_vs_Scr/res_tbl_signif.csv")
res_tbl1 <-  res_tbl %>% filter(!is.na(ENTREZID), padj<0.05)

```

# Introduction

Data from  RAB : CD8+ T cells from mice

- Cell types: not nucleofected, scramble, Ndufa2 KO, Mrpl28 KO

-   Conditions: treated w/ or w/o Tryptophan (4 um vs 70 uM)

-   Biological replicates (3)

# Volcano plot 

```{r, fig.height = 6, fig.width = 7}

res_tbl %>%
  filter(!is.na(padj)) %>%
  ggplot(aes(x = log2FoldChange, y = -log10(padj),
             color = padj < 0.05 & abs(log2FoldChange) > 1, 
             label = ifelse(padj<0.05&log2FoldChange>=1|
                              padj<0.05&log2FoldChange<=-1,as.character(gene),''))) +
  scale_colour_manual(values = c("gray", "firebrick3")) +
  labs(col="Significantly expressed")+
  geom_point(size = 0.5) +
  geom_hline(yintercept = -log10(0.05)) +
  geom_vline(xintercept = 1) +
  geom_vline(xintercept = -1)+
  geom_text_repel(max.overlaps = 15,
                  box.padding = 0.25,
                  segment.color = 'grey50',
                  fontface = "italic")+
  labs(title = "Mrpl28 KO vs scramble cells in Trp- medium")+
  theme_bw()

```

Getting some stats yay

```{r, echo=TRUE}

table(res_tbl$padj<=0.05) # significant genes

table(res_tbl$padj<=0.05&res_tbl$log2FoldChange<=-1) # signif and downreg

table(res_tbl$padj<=0.05&res_tbl$log2FoldChange>=1) # signif and upreg

```


```{r}

res_tbl1 %>% 
  select(ensembl, log2FoldChange, padj, gene, description) %>% 
  knitr::kable()

```




